config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :servings
  root "servings#index"
  get "/foods/new", to: "foods#new"
  post "/foods", to: "foods#create"
  #TODO :- Work on update
  # put "/foods/:id", to: "foods#update"
  # patch "/foods/:id", to: "foods#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  has_many :foods, through: :servings
end

app/models/food.rb
class Food < ApplicationRecord
  validates :name, presence: {message: "Name connot be blank"}
  validates :category, presence: {message: "Category shouldn't be blank"}
  validates :calories, presence: {message: "Calories shouldn't be blank"}, numericality: {greater_than_or_equal_to: 0, only_integer: true}
  has_one :day, through: :serving

  @serving = 0
  def food_serving
    @serving ? @serving : nil
  end

  def food_serving=(serving)
    @serving = serving
  end
end

app/models/serving.rb
class Serving < ApplicationRecord
  validates :serving, presence: {message: "Cannot leave servings blank."}, numericality: {greater_than_or_equal_to: 0.01}
  belongs_to :food, optional: true
  belongs_to :day, optional: true

  def food_name
    self.food ? self.food.name : nil
  end

  def food_name=(name)
    self.food = Food.find_by(name: name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # GET /foods/new
  def new
    @food = Food.new
    @food.food_serving = params[:serving]
    @food.name = params[:food_name]
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)
    @serving = Serving.new({:serving => @food.food_serving})
    @serving.food = @food
    if @serving.save
    end
    respond_to do |format|
      if @food.save
        format.html { redirect_to servings_url}
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  #TODO :- work on update
  # def update
  #   respond_to do |format|
  #     if @food.update(food_params)
  #       format.html { redirect_to servings_url, notice: 'Food was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @food }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @food.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end


  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit( :name, :category,:calories,:carbohydrates,
        :protein,:fat, :food_serving)
    end
end

app/controllers/servings_controller.rb
class ServingsController < ApplicationController
  before_action :set_serving, only: [:show, :edit, :update, :destroy]

  # GET /servings
  # GET /servings.json
  def index
    @servings = Serving.all
  end

  # GET /servings/1
  # GET /servings/1.json
  def show
  end

  # GET /servings/new
  def new
    @serving = Serving.new # Only use because view uses @serving
  end

  # GET /servings/1/edit
  def edit
  end

  # POST /servings
  # POST /servings.json
  def create
    @serving = Serving.new(serving_params)
    if !(@serving.food_name)
      session[:serving_quantity] = params[:serving]
      redirect_to foods_new_url(serving_params)

    else
      respond_to do |format|
        if @serving.save
          format.html { redirect_to @serving, notice: 'Serving was successfully created.' }
          format.json { render :show, status: :created, location: @serving }
        else
          format.html { render :new }
          format.json { render json: @serving.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /servings/1
  # PATCH/PUT /servings/1.json
  def update
    respond_to do |format|
      if @serving.update(serving_params)
        format.html { redirect_to @serving, notice: 'Serving was successfully updated.' }
        format.json { render :show, status: :ok, location: @serving }
      else
        format.html { render :edit }
        format.json { render json: @serving.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servings/1
  # DELETE /servings/1.json
  def destroy
    @serving.destroy
    respond_to do |format|
      format.html { redirect_to servings_url, notice: 'Serving was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_serving
      @serving = Serving.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def serving_params
      params.require(:serving).permit(:serving, :food_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/servings_helper.rb
module ServingsHelper
end

app/views/foods/_form.html.haml
= form_for @food do |f|
  - if @food.errors.any?
    #error_explanation
      %h2= "#{pluralize(@food.errors.count, "error")} prohibited this food from being saved:"
      %ul
        - @food.errors.full_messages.each do |message|
          %li= message

  %ol.inputs
    %li
      = f.label :name, "Food Name"
      = f.text_field :name
    %li
      = f.label :food_serving, "Serving"
      = f.text_field :food_serving
    %li
      = f.label :category
      = f.text_field :category
    %li
      = f.label :calories
      = f.text_field :calories
    %li
      = f.label :carbohydrates
      = f.text_field :carbohydrates
    %li
      = f.label :protein
      = f.text_field :protein
    %li
      = f.label :fat
      = f.text_field :fat
    %li.actions
      = f.submit 'Save'

app/views/foods/edit.html.haml
%h1 Editing food

= render 'form'

= link_to 'Show', @food
\|
= link_to 'Back', foods_path

app/views/foods/new.html.haml
%p.food_not_found The food you entered wasn't found, please enter details below.

= render 'form'

%footer
  %ul.controls
    %li#back_btn_new_food= link_to 'Back', servings_path

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset:"UTF-8"}
    %title Alpha
    %meta{name: "viewport", content:"width=device-width,initial-scale=1.0,shrink-to-fit=no"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header#header
      %h1 Food Tracker
      %p.tagline Know you're eating healthy
    = yield
    %footer#footer
      %small Designed and developed by Mahmoud Kahack. All rights reserved.

app/views/servings/_form.html.haml
= form_for @serving do |f|
  - if @serving.errors.any?
    #error_explanation
      %h2= "#{pluralize(@serving.errors.count, "error")} prohibited this serving from being saved:"
      %ul
        - @serving.errors.full_messages.each do |message|
          %li= message

  %ol.inputs
    %li
      = f.label :food_name, "Food Name"
      = f.text_field :food_name
    %li
      = f.label :serving
      = f.text_field :serving
    %li.actions
      = f.submit 'Save'

app/views/servings/edit.html.haml
%h2.form_title Editing serving

= render 'form'

%footer
  %ul.controls
    %li#back_btn_new_serv= link_to 'Back', servings_path

app/views/servings/index.html.haml
%h2#title_food_index Your Food
%ul.controls
  %li#new_serving_btn= link_to 'Add New Item', new_serving_path
%table
  -# %thead
  -#   %tr
  -#     %th Name
  -#     %th Serving
  -#     %th Calories
      -# %th
      -# %th
      -# %th

  %tbody
    - @servings.each do |serving|
      %tr
        %td.food_name= link_to serving.food_name, serving
        %td.desktop_items.right_align= serving.food.carbohydrates.to_s + "g of Carbohydrates"
        %td.desktop_items.right_align= serving.food.fat.to_s + "g of Fat"
        %td.desktop_items.right_align=serving.food.protein.to_s + "g of Protein"
        %td.right_align= serving.food.calories.to_s + " cal"
        %td.right_align
          -# = link_to 'Show', serving
          = link_to image_tag("edit.png"), edit_serving_path(serving)
          = link_to image_tag("trash.png"), serving, method: :delete, data: { confirm: 'Are you sure?' }
      %tr.entry_actions
        -#TODO: include icons for actions.
        %td= serving.serving.to_s + " serving"

        %td
        %td

%br

app/views/servings/new.html.haml
%h2.form_title New serving

= render 'form'

%footer
  %ul.controls
    %li#back_btn_new_serv= link_to 'Back', servings_path

app/views/servings/show.html.haml
%ul
  %li
    %h3.food_name= @serving.food.name
  %li
    %h3 Serving:
    %p= @serving.serving
  %li
    %h3 Category:
    %p= @serving.food.category
  %li
    %h3 Calories:
    %p= @serving.food.calories.to_s + " cal"
  %li
    %h3 Carbs:
    %p= @serving.food.carbohydrates.to_s + "g"
  %li
    %h3 Proteins:
    %p= @serving.food.protein.to_s + "g"
  %li
    %h3 Fats:
    %p= @serving.food.fat.to_s + "g"
%ul.controls
  %li
    = link_to 'Back', servings_path
    = link_to 'Edit', edit_serving_path(@serving)
    = link_to 'Delete', @post, method: :delete, data:{confirm: 'Are you sure?'}